// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adpxtjnsdpxamceaqqvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkcHh0am5zZHB4YW1jZWFxcXZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NTc1MzYsImV4cCI6MjA2MDQzMzUzNn0.z4N72qEf9wgUrGputw-g7MgyE59QSCTeJNThEqoo9-s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);